vm:
  keys:
    jorgecarleitao: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMMlhFA81TvA9BBMBJlPcXyEIbcVG5OODkOy03scUvfL jorgecarleitao@gmail.com
    github-actions: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO4Y0fy3IorNp7S2xh/PKNcjV2GS7hr4Dfneh3YP0btp jorgecarleitao@gmail.com
  server_type: cx32
  location: fsn1
cloudflare:
  account_id: "0437df3d3066f074c8f1055ebcac579c"
  zones:
    stvote.eu: null
